# build environment
FROM node:14-stretch as build

WORKDIR /app

COPY package.json ./
COPY yarn.lock ./
COPY . ./

RUN yarn install
RUN yarn build

 # production environment
FROM nginx:stable-alpine as nginx
FROM alpine:3.11
COPY --from=nginx / /
COPY --from=build /app/nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/public /usr/share/nginx/html
EXPOSE 81
CMD ["nginx", "-g", "daemon off;"]